notifications:
  email: false
language: node_js
node_js:
  - "4.0"
before_script:
  - npm install -g electron-prebuilt
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8b150eaf525c280ec2ac
    on_success: change
    on_failure: always
    on_start: never
